### PR TITLE
Create acceptance test helper to fill in a content editable component

### PR DESCRIPTION
**Pull request by Gaurav0**
Fixes issue #24 with a cool reusable acceptance test helper and acceptance test for the dummy app demonstrating how to use it.

### CODE REVIEW

**Comment by Gaurav0** [comment]
Update: Included @ConorLinehan 's fix and fixed tests for Ember 2.7

**Comment by Gaurav0** [comment]
ember try:testall passes for me locally. Not sure why it does not pass on Travis.

**Comment by Gaurav0** [comment]
Yay! Tests Passed!

**Comment by chrissloey** [comment]
Great, thanks for this! Looks awesome. I'll get it released as 0.10.0

**Pull request merged**
